---
title: "Statistical Inference - Logistic Regression"
author: "Ian Dinwoodie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)

knitr::opts_chunk$set(echo=TRUE)
set.seed(1)
```

# Preparing the Data

## Loading the Tidy Data

Load the tidy data from disk.

```{r}
df <- readRDS('../data/processed/tidy.Rds')
#stopifnot(identical(dim(df)+0, c(1543, 28)))
str(df, list.len=5)
```

## Data Preperation

Drop entries where the sum of ranks for an entry does not match the expected
value.

```{r}
# full_cnt <- dim(df)[1]
# 
# df <- df %>%
#   rowwise() %>%
#     mutate(rank_sum = sum(c_across(age_rank:trainability_rank))) %>%
#   ungroup() %>%
#   filter(rank_sum == 28) %>%
#   dplyr::select(-rank_sum)
# 
# print(paste("Count of improperly ranked responses:", full_cnt - dim(df)[1]))
```

Drop columns that won't be used by the inferential models.

```{r}
df <- df %>%
  dplyr::select(-c(
    owner_id,
    dog_name,
    time_together_len,
    revised_acquisition_source,
    #is_living_with_dog,
    curr_dog_location,
    met_expectations,
    is_consider_another_dog
  )) %>%
  dplyr::select(-contains("revised"))

dim(df)
summary(df)
```

Remove problematic variables and rows with missing values.

```{r}
df <- df %>%
  #dplyr::select(-trainability_rank) %>%
  #dplyr::select(-is_male) %>%
  mutate(is_satisfied = as.factor(is_satisfied)) %>%
  #mutate(is_satisfied = as.factor(ifelse(is_satisfied, "yes", "no"))) %>%
  drop_na()
```

# Inference



## Preprocessing

```{r}
mm <- model.matrix(is_satisfied~.-1, df)
str(mm)
```

```{r}
# Eliminate near zero-variance variables.
(nzv_metrics <- nearZeroVar(mm, saveMetrics=TRUE))
nzv_cnt <- sum(nzv_metrics$nzv)
print(paste("Near zero-variance vars to eliminate:", nzv_cnt))
if (nzv_cnt) {
  print(colnames(mm[, nzv_metrics$nzv]))
  mm <- mm[, !nzv_metrics$nzv]
}

# Eliminate linearly correlated predictors.
combo_info <- findLinearCombos(mm)
combo_cnt <- length(combo_info$remove)
print(paste("Linearly corr. combos vars to eliminate:", combo_cnt))
if (combo_cnt) {
  print(colnames(mm[, combo_info$remove]))
  mm <- mm[, -combo_info$remove]
}
```

```{r}
df <- cbind.data.frame(is_satisfied=df$is_satisfied, mm)
colnames(df) <- make.names(colnames(df))
dim(df)
summary(df)
```

# Save Session Info

```{r}
sessionInfo()
```
